

mqnotifysig1: mqnotifysig1.c ../lib/wrap.h
	gcc -o mqnotifysig1 mqnotifysig1.c -include ../lib/wrap.h -lrt

mqgetattr: mqgetattr.c ../lib/wrap.h
	gcc -o mqgetattr mqgetattr.c -include ../lib/wrap.h -lrt
mqsend: mqsend.c ../lib/wrap.h
	gcc -o mqsend mqsend.c -include ../lib/wrap.h -lrt
mqcreate: mqcreate1.c ../lib/wrap.h
	gcc -o mqcreate mqcreate1.c -include ../lib/wrap.h -lrt
mqunlink: mqunlink.c ../lib/wrap.h
	gcc -o mqunlink mqunlink.c -include ../lib/wrap.h -lrt